### PR TITLE
Fix dict_RemoveKeyValue

### PR DESCRIPTION
**Pull request by yaaacov**
No need to remove 1 to dict_Index

### CODE REVIEW

**Comment by timhall** [comment]
Thanks for the PR @yaaacov! I'll review it shortly

**Comment by yaaacov** [comment]
Hi Tim,
Any news for that fix? It fixed an issue on my particular macro.. but it definitely needs a quick review.
Thanks for tools anyway!

**Comment by timhall** [comment]
What issue did you run into? (I'd like to add a test case for it)

**Comment by timhall** [comment]
Hmm, there seem to be some other indexing issues with `Keys` and `Items`, I'm continuing to look into it

**Pull request closed without merging**
